"""user ip,faild login,is_locker

Revision ID: 5380e4420e0f
Revises: a361b3d352e7
Create Date: 2026-03-12 11:35:10.421967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5380e4420e0f'
down_revision: Union[str, None] = 'a361b3d352e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_failed_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ip_address')
    op.drop_column('users', 'last_failed_login_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'is_locked')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
