"""all, delete-orphan usermodel

Revision ID: e9e9eb0afafc
Revises: 9dbafb10757e
Create Date: 2026-03-11 15:56:36.066471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e9eb0afafc'
down_revision: Union[str, None] = '9dbafb10757e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
